// Generated by scripts/generate-ipc-commands.mjs. Do not edit manually.

export const IPC_COMMANDS = {
    add_atom: 'add_atom',
    add_measurement: 'add_measurement',
    apply_cell_standardize: 'apply_cell_standardize',
    apply_niggli_reduce: 'apply_niggli_reduce',
    apply_slab: 'apply_slab',
    apply_supercell: 'apply_supercell',
    check_api_key_status: 'check_api_key_status',
    clear_measurements: 'clear_measurements',
    clear_wannier: 'clear_wannier',
    compute_brillouin_zone: 'compute_brillouin_zone',
    delete_atoms: 'delete_atoms',
    export_file: 'export_file',
    export_image: 'export_image',
    generate_kpath_text: 'generate_kpath_text',
    get_bond_analysis: 'get_bond_analysis',
    get_bz_label_positions: 'get_bz_label_positions',
    get_crystal_state: 'get_crystal_state',
    get_kpath_info: 'get_kpath_info',
    get_measurement_labels_screen: 'get_measurement_labels_screen',
    get_measurements: 'get_measurements',
    get_settings: 'get_settings',
    get_volumetric_info: 'get_volumetric_info',
    llm_chat: 'llm_chat',
    llm_configure: 'llm_configure',
    llm_execute_command: 'llm_execute_command',
    load_axsf_phonon: 'load_axsf_phonon',
    load_cif_file: 'load_cif_file',
    load_phonon: 'load_phonon',
    load_phonon_interactive: 'load_phonon_interactive',
    load_volumetric_file: 'load_volumetric_file',
    load_wannier_hr: 'load_wannier_hr',
    pan_camera: 'pan_camera',
    pick_atom: 'pick_atom',
    preview_slab: 'preview_slab',
    preview_supercell: 'preview_supercell',
    redo: 'redo',
    reset_camera: 'reset_camera',
    restore_unitcell: 'restore_unitcell',
    rotate_camera: 'rotate_camera',
    set_bz_scale: 'set_bz_scale',
    set_camera_projection: 'set_camera_projection',
    set_camera_view_axis: 'set_camera_view_axis',
    set_isosurface_color: 'set_isosurface_color',
    set_isosurface_opacity: 'set_isosurface_opacity',
    set_isosurface_sign_mode: 'set_isosurface_sign_mode',
    set_isovalue: 'set_isovalue',
    set_phonon_mode: 'set_phonon_mode',
    set_phonon_phase: 'set_phonon_phase',
    set_render_flags: 'set_render_flags',
    set_volume_colormap: 'set_volume_colormap',
    set_volume_density_cutoff: 'set_volume_density_cutoff',
    set_volume_opacity_range: 'set_volume_opacity_range',
    set_volume_render_mode: 'set_volume_render_mode',
    set_wannier_orbital: 'set_wannier_orbital',
    set_wannier_r_shell: 'set_wannier_r_shell',
    set_wannier_t_min: 'set_wannier_t_min',
    shift_termination: 'shift_termination',
    substitute_atoms: 'substitute_atoms',
    toggle_bz_display: 'toggle_bz_display',
    toggle_hopping_display: 'toggle_hopping_display',
    toggle_wannier_onsite: 'toggle_wannier_onsite',
    translate_atoms_screen: 'translate_atoms_screen',
    undo: 'undo',
    update_lattice_params: 'update_lattice_params',
    update_selection: 'update_selection',
    update_settings: 'update_settings',
    update_viewport_size: 'update_viewport_size',
    write_text_file: 'write_text_file',
    zoom_camera: 'zoom_camera',
} as const;

export type IpcCommandName = typeof IPC_COMMANDS[keyof typeof IPC_COMMANDS];

export interface GeneratedIpcCommandArgs {
    add_atom: { atomicNumber: unknown; elementSymbol: unknown; fractPos: unknown };
    add_measurement: { indices: unknown };
    apply_cell_standardize: { toPrimitive: unknown };
    apply_niggli_reduce: undefined;
    apply_slab: { layers: unknown; miller: unknown; vacuumA: unknown };
    apply_supercell: { matrix: unknown };
    check_api_key_status: { providerType: unknown };
    clear_measurements: undefined;
    clear_wannier: undefined;
    compute_brillouin_zone: undefined;
    delete_atoms: { indices: unknown };
    export_file: { format: unknown; path: unknown };
    export_image: { bgMode: unknown; height: unknown; path: unknown; width: unknown };
    generate_kpath_text: { npoints: unknown };
    get_bond_analysis: { thresholdFactor: unknown };
    get_bz_label_positions: { height: unknown; width: unknown };
    get_crystal_state: undefined;
    get_kpath_info: undefined;
    get_measurement_labels_screen: { height: unknown; width: unknown };
    get_measurements: undefined;
    get_settings: undefined;
    get_volumetric_info: undefined;
    llm_chat: { selectedIndices: unknown; userMessage: unknown };
    llm_configure: { apiKey: unknown; model: unknown; providerType: unknown };
    llm_execute_command: { commandJson: unknown };
    load_axsf_phonon: { path: unknown };
    load_cif_file: { path: unknown };
    load_phonon: { path: unknown };
    load_phonon_interactive: { modes: unknown; scfIn: unknown; scfOut: unknown };
    load_volumetric_file: { path: unknown };
    load_wannier_hr: { path: unknown };
    pan_camera: { dx: unknown; dy: unknown };
    pick_atom: { screenH: unknown; screenW: unknown; x: unknown; y: unknown };
    preview_slab: { layers: unknown; miller: unknown; vacuumA: unknown };
    preview_supercell: { expansion: unknown };
    redo: undefined;
    reset_camera: undefined;
    restore_unitcell: undefined;
    rotate_camera: { dx: unknown; dy: unknown };
    set_bz_scale: { scale: unknown };
    set_camera_projection: { isPerspective: unknown };
    set_camera_view_axis: { axis: unknown };
    set_isosurface_color: { color: unknown };
    set_isosurface_opacity: { opacity: unknown };
    set_isosurface_sign_mode: { mode: unknown };
    set_isovalue: { value: unknown };
    set_phonon_mode: { modeIndex: unknown };
    set_phonon_phase: { amplitude: unknown; phase: unknown };
    set_render_flags: { showBonds: unknown; showCell: unknown };
    set_volume_colormap: { mode: unknown };
    set_volume_density_cutoff: { cutoff: unknown };
    set_volume_opacity_range: { max: unknown; min: unknown; opacityScale: unknown };
    set_volume_render_mode: { mode: unknown };
    set_wannier_orbital: { active: unknown; orbIdx: unknown };
    set_wannier_r_shell: { active: unknown; shellIdx: unknown };
    set_wannier_t_min: { tMin: unknown };
    shift_termination: { layerToleranceA: unknown; targetLayerIdx: unknown };
    substitute_atoms: { indices: unknown; newAtomicNumber: unknown; newElementSymbol: unknown };
    toggle_bz_display: { show: unknown };
    toggle_hopping_display: { show: unknown };
    toggle_wannier_onsite: { show: unknown };
    translate_atoms_screen: { dx: unknown; dy: unknown; indices: unknown };
    undo: undefined;
    update_lattice_params: { a: unknown; alpha: unknown; b: unknown; beta: unknown; c: unknown; gamma: unknown };
    update_selection: { indices: unknown };
    update_settings: { newSettings: unknown };
    update_viewport_size: { height: unknown; width: unknown };
    write_text_file: { content: unknown; path: unknown };
    zoom_camera: { delta: unknown };
}

export type GeneratedIpcArgs<Command extends IpcCommandName> = GeneratedIpcCommandArgs[Command];
