//! Format exporters for CrystalCanvas
use crate::crystal_state::CrystalState;
use std::collections::HashMap;
use std::fs::File;
use std::io::{self, Write};

/// Export to VASP POSCAR format (Fractional/Direct coordinates)
pub fn export_poscar(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    
    writeln!(file, "{} generated by CrystalCanvas", state.name)?;
    writeln!(file, "1.0")?;
    
    let a = state.cell_a;
    let b = state.cell_b;
    let c = state.cell_c;
    let alpha = state.cell_alpha.to_radians();
    let beta = state.cell_beta.to_radians();
    let gamma = state.cell_gamma.to_radians();

    let cx = c * beta.cos();
    let cy = c * (alpha.cos() - beta.cos() * gamma.cos()) / gamma.sin();
    let cz = (c * c - cx * cx - cy * cy).sqrt();

    writeln!(file, "  {:.6} {:.6} {:.6}", a, 0.0, 0.0)?;
    writeln!(file, "  {:.6} {:.6} {:.6}", b * gamma.cos(), b * gamma.sin(), 0.0)?;
    writeln!(file, "  {:.6} {:.6} {:.6}", cx, cy, cz)?;

    // Aggregate atoms by element preserving order of first appearance
    let mut ordered_elements = Vec::new();
    let mut atom_groups: HashMap<String, Vec<[f64; 3]>> = HashMap::new();
    
    for i in 0..state.num_atoms() {
        let elem = &state.elements[i];
        if !atom_groups.contains_key(elem) {
            ordered_elements.push(elem.clone());
            atom_groups.insert(elem.clone(), Vec::new());
        }
        atom_groups.get_mut(elem).unwrap().push([state.fract_x[i], state.fract_y[i], state.fract_z[i]]);
    }
    
    for elem in &ordered_elements {
        write!(file, "{} ", elem)?;
    }
    writeln!(file)?;
    
    for elem in &ordered_elements {
        write!(file, "{} ", atom_groups.get(elem).unwrap().len())?;
    }
    writeln!(file)?;
    
    writeln!(file, "Direct")?;
    for elem in &ordered_elements {
        for pos in atom_groups.get(elem).unwrap() {
            writeln!(file, "  {:.6} {:.6} {:.6}", pos[0], pos[1], pos[2])?;
        }
    }
    
    Ok(())
}

/// Export to LAMMPS Data format
pub fn export_lammps_data(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    
    writeln!(file, "LAMMPS data file generated by CrystalCanvas")?;
    writeln!(file)?;
    
    writeln!(file, "{} atoms", state.num_atoms())?;
    
    // Unique atom types
    let mut ordered_elements = Vec::new();
    let mut type_map: HashMap<String, usize> = HashMap::new();
    for elem in &state.elements {
        if !type_map.contains_key(elem) {
            ordered_elements.push(elem.clone());
            type_map.insert(elem.clone(), ordered_elements.len());
        }
    }
    writeln!(file, "{} atom types", ordered_elements.len())?;
    writeln!(file)?;
    
    let a = state.cell_a;
    let b = state.cell_b;
    let c = state.cell_c;
    let alpha = state.cell_alpha.to_radians();
    let beta = state.cell_beta.to_radians();
    let gamma = state.cell_gamma.to_radians();

    let lx = a;
    let xy = b * gamma.cos();
    let xz = c * beta.cos();
    let ly = (b * b - xy * xy).sqrt();
    let yz = (b * c * alpha.cos() - xy * xz) / ly;
    let lz = (c * c - xz * xz - yz * yz).sqrt();

    writeln!(file, "0.0 {:.6} xlo xhi", lx)?;
    writeln!(file, "0.0 {:.6} ylo yhi", ly)?;
    writeln!(file, "0.0 {:.6} zlo zhi", lz)?;
    writeln!(file, "{:.6} {:.6} {:.6} xy xz yz", xy, xz, yz)?;
    writeln!(file)?;
    
    // Masses block
    writeln!(file, "Masses")?;
    writeln!(file)?;
    for (i, elem) in ordered_elements.iter().enumerate() {
        // Just writing a dummy mass of 1.0; usually LAMMPS requires real masses
        // Without an internal mass table, we output 1.0 as placeholder.
        writeln!(file, "{} 1.000 # {}", i + 1, elem)?;
    }
    writeln!(file)?;
    
    // Atoms block (atomic style: atom-ID atom-type x y z)
    writeln!(file, "Atoms # atomic")?;
    writeln!(file)?;
    
    for i in 0..state.num_atoms() {
        let elem = &state.elements[i];
        let type_id = type_map.get(elem).unwrap();
        
        let fx = state.fract_x[i];
        let fy = state.fract_y[i];
        let fz = state.fract_z[i];
        
        // Convert fractional to LAMMPS cartesian
        let x = lx * fx + xy * fy + xz * fz;
        let y = ly * fy + yz * fz;
        let z = lz * fz;
        
        writeln!(file, "{} {} {:.6} {:.6} {:.6}", i + 1, type_id, x, y, z)?;
    }
    
    Ok(())
}

/// Export to Quantum ESPRESSO format
pub fn export_qe_input(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    
    let mut ordered_elements = Vec::new();
    let mut type_map: HashMap<String, usize> = HashMap::new();
    for elem in &state.elements {
        if !type_map.contains_key(elem) {
            ordered_elements.push(elem.clone());
            type_map.insert(elem.clone(), ordered_elements.len());
        }
    }
    
    writeln!(file, "&CONTROL")?;
    writeln!(file, "  calculation = 'scf'")?;
    writeln!(file, "  prefix = '{}'", state.name)?;
    writeln!(file, "  pseudo_dir = './'")?;
    writeln!(file, "  outdir = './'")?;
    writeln!(file, "/")?;
    
    writeln!(file, "&SYSTEM")?;
    writeln!(file, "  ibrav = 0")?;
    writeln!(file, "  nat = {}", state.num_atoms())?;
    writeln!(file, "  ntyp = {}", ordered_elements.len())?;
    writeln!(file, "/")?;
    
    writeln!(file, "&ELECTRONS")?;
    writeln!(file, "/")?;
    
    writeln!(file, "ATOMIC_SPECIES")?;
    for elem in &ordered_elements {
        writeln!(file, "  {} 1.000 {}.UPF", elem, elem)?;
    }
    
    let a = state.cell_a;
    let b = state.cell_b;
    let c = state.cell_c;
    let alpha = state.cell_alpha.to_radians();
    let beta = state.cell_beta.to_radians();
    let gamma = state.cell_gamma.to_radians();

    let cx = c * beta.cos();
    let cy = c * (alpha.cos() - beta.cos() * gamma.cos()) / gamma.sin();
    let cz = (c * c - cx * cx - cy * cy).sqrt();

    writeln!(file, "CELL_PARAMETERS {{angstrom}}")?;
    writeln!(file, "  {:.6} {:.6} {:.6}", a, 0.0, 0.0)?;
    writeln!(file, "  {:.6} {:.6} {:.6}", b * gamma.cos(), b * gamma.sin(), 0.0)?;
    writeln!(file, "  {:.6} {:.6} {:.6}", cx, cy, cz)?;

    writeln!(file, "ATOMIC_POSITIONS {{crystal}}")?;
    for i in 0..state.num_atoms() {
        writeln!(file, "  {} {:.6} {:.6} {:.6}", 
            state.elements[i], state.fract_x[i], state.fract_y[i], state.fract_z[i])?;
    }
    
    Ok(())
}
