//! Format exporters for CrystalCanvas
use crate::crystal_state::CrystalState;
use std::collections::HashMap;
use std::fs::File;
use std::io::{self, Write};

/// Export to VASP POSCAR format (Fractional/Direct coordinates)
pub fn export_poscar(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    
    writeln!(file, "{} generated by CrystalCanvas", state.name)?;
    writeln!(file, "1.0")?;
    
    let a = state.cell_a;
    let b = state.cell_b;
    let c = state.cell_c;
    let alpha = state.cell_alpha.to_radians();
    let beta = state.cell_beta.to_radians();
    let gamma = state.cell_gamma.to_radians();

    let cx = c * beta.cos();
    let cy = c * (alpha.cos() - beta.cos() * gamma.cos()) / gamma.sin();
    let cz = (c * c - cx * cx - cy * cy).sqrt();

    writeln!(file, "  {:.6} {:.6} {:.6}", a, 0.0, 0.0)?;
    writeln!(file, "  {:.6} {:.6} {:.6}", b * gamma.cos(), b * gamma.sin(), 0.0)?;
    writeln!(file, "  {:.6} {:.6} {:.6}", cx, cy, cz)?;

    // Aggregate atoms by element preserving order of first appearance
    let mut ordered_elements = Vec::new();
    let mut atom_groups: HashMap<String, Vec<[f64; 3]>> = HashMap::new();
    
    for i in 0..state.num_atoms() {
        let elem = &state.elements[i];
        if !atom_groups.contains_key(elem) {
            ordered_elements.push(elem.clone());
            atom_groups.insert(elem.clone(), Vec::new());
        }
        atom_groups.get_mut(elem).unwrap().push([state.fract_x[i], state.fract_y[i], state.fract_z[i]]);
    }
    
    for elem in &ordered_elements {
        write!(file, "{} ", elem)?;
    }
    writeln!(file)?;
    
    for elem in &ordered_elements {
        write!(file, "{} ", atom_groups.get(elem).unwrap().len())?;
    }
    writeln!(file)?;
    
    writeln!(file, "Direct")?;
    for elem in &ordered_elements {
        for pos in atom_groups.get(elem).unwrap() {
            writeln!(file, "  {:.6} {:.6} {:.6}", pos[0], pos[1], pos[2])?;
        }
    }
    
    Ok(())
}

/// Export to LAMMPS Data format
pub fn export_lammps_data(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    
    writeln!(file, "# LAMMPS data file generated by CrystalCanvas")?;
    writeln!(file, "# WARNING: This is a geometry template. Check 'Masses' and atom styles/coeffs.")?;
    writeln!(file)?;
    
    writeln!(file, "{} atoms", state.num_atoms())?;
    
    // Unique atom types
    let mut ordered_elements = Vec::new();
    let mut type_map: HashMap<String, usize> = HashMap::new();
    for elem in &state.elements {
        if !type_map.contains_key(elem) {
            ordered_elements.push(elem.clone());
            type_map.insert(elem.clone(), ordered_elements.len());
        }
    }
    writeln!(file, "{} atom types", ordered_elements.len())?;
    writeln!(file)?;
    
    let a = state.cell_a;
    let b = state.cell_b;
    let c = state.cell_c;
    let alpha = state.cell_alpha.to_radians();
    let beta = state.cell_beta.to_radians();
    let gamma = state.cell_gamma.to_radians();

    let lx = a;
    let xy = b * gamma.cos();
    let xz = c * beta.cos();
    let ly = (b * b - xy * xy).sqrt();
    let yz = (b * c * alpha.cos() - xy * xz) / ly;
    let lz = (c * c - xz * xz - yz * yz).sqrt();

    writeln!(file, "0.0 {:.6} xlo xhi", lx)?;
    writeln!(file, "0.0 {:.6} ylo yhi", ly)?;
    writeln!(file, "0.0 {:.6} zlo zhi", lz)?;
    writeln!(file, "{:.6} {:.6} {:.6} xy xz yz", xy, xz, yz)?;
    writeln!(file)?;
    
    // Masses block
    writeln!(file, "Masses")?;
    writeln!(file)?;
    for (i, elem) in ordered_elements.iter().enumerate() {
        let mass = get_atomic_mass(elem);
        writeln!(file, "{} {:.5} # {}", i + 1, mass, elem)?;
    }
    writeln!(file)?;
    
    // Atoms block (atomic style: atom-ID atom-type x y z)
    writeln!(file, "Atoms # atomic")?;
    writeln!(file)?;
    
    for i in 0..state.num_atoms() {
        let elem = &state.elements[i];
        let type_id = type_map.get(elem).unwrap();
        
        let fx = state.fract_x[i];
        let fy = state.fract_y[i];
        let fz = state.fract_z[i];
        
        // Convert fractional to LAMMPS cartesian
        let x = lx * fx + xy * fy + xz * fz;
        let y = ly * fy + yz * fz;
        let z = lz * fz;
        
        writeln!(file, "{} {} {:.6} {:.6} {:.6}", i + 1, type_id, x, y, z)?;
    }
    
    Ok(())
}

/// Get standard atomic weights for common elements.
/// Source: IUPAC "Atomic weights of the elements 2021" (CIAAW).
/// Values are in Unified Atomic Mass Units (u).
fn get_atomic_mass(element: &str) -> f64 {
    match element {
        "H" => 1.0078, "He" => 4.0026, "Li" => 6.9410, "Be" => 9.0122, "B" => 10.811, 
        "C" => 12.011, "N" => 14.007, "O" => 15.999, "F" => 18.998, "Ne" => 20.180,
        "Na" => 22.990, "Mg" => 24.305, "Al" => 26.982, "Si" => 28.085, "P" => 30.974, 
        "S" => 32.060, "Cl" => 35.450, "Ar" => 39.948, "K" => 39.098, "Ca" => 40.078,
        "Sc" => 44.956, "Ti" => 47.867, "V" => 50.9415, "Cr" => 51.9961, "Mn" => 54.938, "Fe" => 55.845,
        "Co" => 58.933, "Ni" => 58.693, "Cu" => 63.546, "Zn" => 65.38, "Ga" => 69.723,
        "Ge" => 72.630, "As" => 74.922, "Se" => 78.971, "Br" => 79.904, "Kr" => 83.798,
        "Rb" => 85.468, "Sr" => 87.62, "Y" => 88.906, "Zr" => 91.224, "Nb" => 92.906, "Mo" => 95.95, 
        "Ru" => 101.07, "Rh" => 102.91, "Pd" => 106.42, "Ag" => 107.87, "Cd" => 112.41,
        "In" => 114.82, "Sn" => 118.71, "Sb" => 121.76, "Te" => 127.60, "I" => 126.90, "Xe" => 131.29,
        "Cs" => 132.91, "Ba" => 137.33, "La" => 138.91, "Ce" => 140.12, "Pr" => 140.91,
        "W" => 183.84, "Pt" => 195.08, "Au" => 196.97, "Hg" => 200.59, "Tl" => 204.38, 
        "Pb" => 207.2, "Bi" => 208.98,
        _ => 1.0, // Default for unknown
    }
}

/// Export to Quantum ESPRESSO format
pub fn export_qe_input(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    
    writeln!(file, "! Quantum ESPRESSO input generated by CrystalCanvas")?;
    writeln!(file, "! WARNING: This is a geometry template. Verify all &CONTROL, &SYSTEM, &ELECTRONS parameters.")?;
    writeln!(file)?;
    
    let mut ordered_elements = Vec::new();
    let mut type_map: HashMap<String, usize> = HashMap::new();
    for elem in &state.elements {
        if !type_map.contains_key(elem) {
            ordered_elements.push(elem.clone());
            type_map.insert(elem.clone(), ordered_elements.len());
        }
    }
    
    writeln!(file, "&CONTROL")?;
    writeln!(file, "  title = '{} generated by CrystalCanvas',", state.name)?;
    writeln!(file, "  calculation = 'scf', prefix = '{}', outdir = './tmp', verbosity = 'high',", state.name)?;
    writeln!(file, "  tprnfor = .true., tstress = .true., forc_conv_thr = 1.0d-7, etot_conv_thr = 1.0d-9, nstep = 100,")?;
    writeln!(file, "/")?;
    
    writeln!(file, "&SYSTEM")?;
    writeln!(file, "  ibrav = 0, nat = {}, ntyp = {},", state.num_atoms(), ordered_elements.len())?;
    
    // Provide both vector mode (ibrav=0) and scalar mode (A,B,C...) components.
    // QE prioritizes ibrav=0 if CELL_PARAMETERS is present.
    writeln!(file, "  A = {:.10}, B = {:.10}, C = {:.10},", state.cell_a, state.cell_b, state.cell_c)?;
    writeln!(file, "  cosAB = {:.10}, cosAC = {:.10}, cosBC = {:.10},", 
        state.cell_gamma.to_radians().cos(), 
        state.cell_beta.to_radians().cos(), 
        state.cell_alpha.to_radians().cos())?;
    
    writeln!(file, "  ecutwfc = 60, occupations = 'smearing', smearing = 'gauss', degauss = 1.0d-2,")?;
    writeln!(file, "/")?;
    
    writeln!(file, "&ELECTRONS")?;
    writeln!(file, "  conv_thr = 1.0d-12,")?;
    writeln!(file, "  mixing_beta = 0.3d0,")?;
    writeln!(file, "/")?;
    
    writeln!(file, "&IONS")?;
    writeln!(file, "/")?;
    
    writeln!(file, "&CELL")?;
    writeln!(file, "  press_conv_thr = 0.02,")?;
    writeln!(file, "/")?;
    writeln!(file, "ATOMIC_SPECIES")?;
    for elem in &ordered_elements {
        let mass = get_atomic_mass(elem);
        writeln!(file, "  {} {:.5} {}.upf", elem, mass, elem)?;
    }
    
    let a = state.cell_a;
    let b = state.cell_b;
    let c = state.cell_c;
    let alpha = state.cell_alpha.to_radians();
    let beta = state.cell_beta.to_radians();
    let gamma = state.cell_gamma.to_radians();

    let cx = c * beta.cos();
    let cy = c * (alpha.cos() - beta.cos() * gamma.cos()) / gamma.sin();
    let cz = (c * c - cx * cx - cy * cy).sqrt();

    writeln!(file, "CELL_PARAMETERS (angstrom)")?;
    writeln!(file, "  {:.10} {:.10} {:.10}", a, 0.0, 0.0)?;
    writeln!(file, "  {:.10} {:.10} {:.10}", b * gamma.cos(), b * gamma.sin(), 0.0)?;
    writeln!(file, "  {:.10} {:.10} {:.10}", cx, cy, cz)?;

    writeln!(file, "ATOMIC_POSITIONS (crystal)")?;
    for i in 0..state.num_atoms() {
        writeln!(file, "  {:2} {:.10} {:.10} {:.10}", 
            state.elements[i], state.fract_x[i], state.fract_y[i], state.fract_z[i])?;
    }
    
    writeln!(file, "K_POINTS {{automatic}}")?;
    // Calculate k-points based on a target density of ~30 Angstrom*K
    // This provides a consistent reciprocal space sampling across different cell sizes.
    let k_density = 30.0;
    let nx = (k_density / state.cell_a).round().max(1.0) as i32;
    let ny = (k_density / state.cell_b).round().max(1.0) as i32;
    let nz = (k_density / state.cell_c).round().max(1.0) as i32;
    writeln!(file, "  {} {} {} 0 0 0", nx, ny, nz)?;
    
    Ok(())
}

/* 
 * FUTURE: Extensibility points for more DFT/MD templates
 * -----------------------------------------------------
 * TODO: Abinit (.in)
 * TODO: ORCA (.inp)
 * TODO: CP2K (.inp)
 */
