//! Format exporters for CrystalCanvas - Strong-typed Writer Implementations
use crate::crystal_state::CrystalState;
use std::collections::HashMap;
use std::fs::File;
use std::io::{self, Write};

/// Abstract structure representing a VASP POSCAR file
pub struct PoscarFile {
    pub comment: String,
    pub scaling_factor: f64,
    pub lattice: [[f64; 3]; 3],
    pub elements: Vec<String>,
    pub element_counts: Vec<usize>,
    pub coordinates: Vec<[f64; 3]>,
}

impl PoscarFile {
    pub fn from_state(state: &CrystalState) -> Self {
        let alpha = state.cell_alpha.to_radians();
        let beta = state.cell_beta.to_radians();
        let gamma = state.cell_gamma.to_radians();
        let c = state.cell_c;

        let cx = c * beta.cos();
        let cy = c * (alpha.cos() - beta.cos() * gamma.cos()) / gamma.sin();
        let cz = (c * c - cx * cx - cy * cy).sqrt();

        let lattice = [
            [state.cell_a, 0.0, 0.0],
            [state.cell_b * gamma.cos(), state.cell_b * gamma.sin(), 0.0],
            [cx, cy, cz],
        ];

        let mut ordered_elements = Vec::new();
        let mut atom_groups: HashMap<String, Vec<[f64; 3]>> = HashMap::new();

        for i in 0..state.num_atoms() {
            let elem = &state.elements[i];
            if !atom_groups.contains_key(elem) {
                ordered_elements.push(elem.clone());
                atom_groups.insert(elem.clone(), Vec::new());
            }
            atom_groups.get_mut(elem).unwrap().push([
                state.fract_x[i],
                state.fract_y[i],
                state.fract_z[i],
            ]);
        }

        let mut counts = Vec::new();
        let mut coordinates = Vec::new();

        for elem in &ordered_elements {
            let group = atom_groups.get(elem).unwrap();
            counts.push(group.len());
            for pos in group {
                coordinates.push(*pos);
            }
        }

        Self {
            comment: format!("{} generated by CrystalCanvas", state.name),
            scaling_factor: 1.0,
            lattice,
            elements: ordered_elements,
            element_counts: counts,
            coordinates,
        }
    }

    pub fn write_to<W: Write>(&self, writer: &mut W) -> io::Result<()> {
        writeln!(writer, "{}", self.comment)?;
        writeln!(writer, "{:.6}", self.scaling_factor)?;
        for row in &self.lattice {
            writeln!(writer, "  {:.6} {:.6} {:.6}", row[0], row[1], row[2])?;
        }
        for elem in &self.elements {
            write!(writer, "{} ", elem)?;
        }
        writeln!(writer)?;
        for count in &self.element_counts {
            write!(writer, "{} ", count)?;
        }
        writeln!(writer)?;
        writeln!(writer, "Direct")?;
        for pos in &self.coordinates {
            writeln!(writer, "  {:.6} {:.6} {:.6}", pos[0], pos[1], pos[2])?;
        }
        Ok(())
    }
}

pub fn export_poscar(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    let poscar = PoscarFile::from_state(state);
    poscar.write_to(&mut file)
}

/// Abstract structure representing a LAMMPS Data file
pub struct LammpsDataFile {
    pub comment: String,
    pub num_atoms: usize,
    pub atom_types: usize,
    pub box_bounds: [([f64; 2], String); 2], // [(min, max), axis] limited to x,y,z and xy,xz,yz
    pub box_x: [f64; 2],
    pub box_y: [f64; 2],
    pub box_z: [f64; 2],
    pub tilts: [f64; 3], // xy, xz, yz
    pub masses: Vec<(usize, f64, String)>,
    pub atoms: Vec<(usize, usize, [f64; 3])>, // id, type, coords
}

impl LammpsDataFile {
    pub fn from_state(state: &CrystalState) -> Self {
        let alpha = state.cell_alpha.to_radians();
        let beta = state.cell_beta.to_radians();
        let gamma = state.cell_gamma.to_radians();
        let b = state.cell_b;
        let c = state.cell_c;

        let lx = state.cell_a;
        let xy = b * gamma.cos();
        let xz = c * beta.cos();
        let ly = (b * b - xy * xy).sqrt();
        let yz = (b * c * alpha.cos() - xy * xz) / ly;
        let lz = (c * c - xz * xz - yz * yz).sqrt();

        let mut ordered_elements = Vec::new();
        let mut type_map: HashMap<String, usize> = HashMap::new();
        for elem in &state.elements {
            if !type_map.contains_key(elem) {
                ordered_elements.push(elem.clone());
                type_map.insert(elem.clone(), ordered_elements.len());
            }
        }

        let mut masses = Vec::new();
        for (i, elem) in ordered_elements.iter().enumerate() {
            masses.push((i + 1, get_atomic_mass(elem), elem.clone()));
        }

        let mut atoms = Vec::new();
        for i in 0..state.num_atoms() {
            let elem = &state.elements[i];
            let type_id = type_map.get(elem).unwrap();

            let fx = state.fract_x[i];
            let fy = state.fract_y[i];
            let fz = state.fract_z[i];

            let x = lx * fx + xy * fy + xz * fz;
            let y = ly * fy + yz * fz;
            let z = lz * fz;

            atoms.push((i + 1, *type_id, [x, y, z]));
        }

        Self {
            comment: "# LAMMPS data file generated by CrystalCanvas\n# WARNING: This is a geometry template. Check 'Masses' and atom styles/coeffs.".to_string(),
            num_atoms: state.num_atoms(),
            atom_types: ordered_elements.len(),
            box_bounds: [([0.0, 0.0], "dummy".to_string()), ([0.0, 0.0], "dummy".to_string())], // Not actually used in write fn
            box_x: [0.0, lx],
            box_y: [0.0, ly],
            box_z: [0.0, lz],
            tilts: [xy, xz, yz],
            masses,
            atoms,
        }
    }

    pub fn write_to<W: Write>(&self, writer: &mut W) -> io::Result<()> {
        writeln!(writer, "{}\n", self.comment)?;
        writeln!(writer, "{} atoms", self.num_atoms)?;
        writeln!(writer, "{} atom types\n", self.atom_types)?;

        writeln!(writer, "0.0 {:.6} xlo xhi", self.box_x[1])?;
        writeln!(writer, "0.0 {:.6} ylo yhi", self.box_y[1])?;
        writeln!(writer, "0.0 {:.6} zlo zhi", self.box_z[1])?;
        writeln!(
            writer,
            "{:.6} {:.6} {:.6} xy xz yz\n",
            self.tilts[0], self.tilts[1], self.tilts[2]
        )?;

        writeln!(writer, "Masses\n")?;
        for m in &self.masses {
            writeln!(writer, "{} {:.5} # {}", m.0, m.1, m.2)?;
        }
        writeln!(writer)?;

        writeln!(writer, "Atoms # atomic\n")?;
        for a in &self.atoms {
            writeln!(
                writer,
                "{} {} {:.6} {:.6} {:.6}",
                a.0, a.1, a.2[0], a.2[1], a.2[2]
            )?;
        }
        Ok(())
    }
}

pub fn export_lammps_data(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    let lammps = LammpsDataFile::from_state(state);
    lammps.write_to(&mut file)
}

fn get_atomic_mass(element: &str) -> f64 {
    match element {
        "H" => 1.0078,
        "He" => 4.0026,
        "Li" => 6.9410,
        "Be" => 9.0122,
        "B" => 10.811,
        "C" => 12.011,
        "N" => 14.007,
        "O" => 15.999,
        "F" => 18.998,
        "Ne" => 20.180,
        "Na" => 22.990,
        "Mg" => 24.305,
        "Al" => 26.982,
        "Si" => 28.085,
        "P" => 30.974,
        "S" => 32.060,
        "Cl" => 35.450,
        "Ar" => 39.948,
        "K" => 39.098,
        "Ca" => 40.078,
        "Sc" => 44.956,
        "Ti" => 47.867,
        "V" => 50.9415,
        "Cr" => 51.9961,
        "Mn" => 54.938,
        "Fe" => 55.845,
        "Co" => 58.933,
        "Ni" => 58.693,
        "Cu" => 63.546,
        "Zn" => 65.38,
        "Ga" => 69.723,
        "Ge" => 72.630,
        "As" => 74.922,
        "Se" => 78.971,
        "Br" => 79.904,
        "Kr" => 83.798,
        "Rb" => 85.468,
        "Sr" => 87.62,
        "Y" => 88.906,
        "Zr" => 91.224,
        "Nb" => 92.906,
        "Mo" => 95.95,
        "Ru" => 101.07,
        "Rh" => 102.91,
        "Pd" => 106.42,
        "Ag" => 107.87,
        "Cd" => 112.41,
        "In" => 114.82,
        "Sn" => 118.71,
        "Sb" => 121.76,
        "Te" => 127.60,
        "I" => 126.90,
        "Xe" => 131.29,
        "Cs" => 132.91,
        "Ba" => 137.33,
        "La" => 138.91,
        "Ce" => 140.12,
        "Pr" => 140.91,
        "W" => 183.84,
        "Pt" => 195.08,
        "Au" => 196.97,
        "Hg" => 200.59,
        "Tl" => 204.38,
        "Pb" => 207.2,
        "Bi" => 208.98,
        _ => 1.0, // Default for unknown
    }
}

/// Abstract structure representing a Quantum ESPRESSO input file
pub struct QeInputFile {
    pub header: String,
    pub title: String,
    pub prefix: String,
    pub ibrav: i32,
    pub num_atoms: usize,
    pub num_types: usize,
    pub cell_abc: [f64; 3],
    pub cell_cos_abc: [f64; 3],
    pub atomic_species: Vec<(String, f64)>,
    pub lattice: [[f64; 3]; 3],
    pub atoms: Vec<(String, [f64; 3])>,
    pub kpoints: [i32; 3],
}

impl QeInputFile {
    pub fn from_state(state: &CrystalState) -> Self {
        let alpha = state.cell_alpha.to_radians();
        let beta = state.cell_beta.to_radians();
        let gamma = state.cell_gamma.to_radians();
        let b = state.cell_b;
        let c = state.cell_c;

        let cx = c * beta.cos();
        let cy = c * (alpha.cos() - beta.cos() * gamma.cos()) / gamma.sin();
        let cz = (c * c - cx * cx - cy * cy).sqrt();

        let lattice = [
            [state.cell_a, 0.0, 0.0],
            [b * gamma.cos(), b * gamma.sin(), 0.0],
            [cx, cy, cz],
        ];

        let mut ordered_elements = Vec::new();
        let mut type_map: HashMap<String, usize> = HashMap::new();
        for elem in &state.elements {
            if !type_map.contains_key(elem) {
                ordered_elements.push(elem.clone());
                type_map.insert(elem.clone(), ordered_elements.len());
            }
        }

        let mut atomic_species = Vec::new();
        for elem in &ordered_elements {
            atomic_species.push((elem.clone(), get_atomic_mass(elem)));
        }

        let mut atoms = Vec::new();
        for i in 0..state.num_atoms() {
            atoms.push((
                state.elements[i].clone(),
                [state.fract_x[i], state.fract_y[i], state.fract_z[i]],
            ));
        }

        let k_density = 30.0;
        let nx = (k_density / state.cell_a).round().max(1.0) as i32;
        let ny = (k_density / state.cell_b).round().max(1.0) as i32;
        let nz = (k_density / state.cell_c).round().max(1.0) as i32;

        Self {
            header: "! Quantum ESPRESSO input generated by CrystalCanvas\n! WARNING: This is a geometry template. Verify all &CONTROL, &SYSTEM, &ELECTRONS parameters.".to_string(),
            title: format!("{} generated by CrystalCanvas", state.name),
            prefix: state.name.clone(),
            ibrav: 0,
            num_atoms: state.num_atoms(),
            num_types: ordered_elements.len(),
            cell_abc: [state.cell_a, state.cell_b, state.cell_c],
            cell_cos_abc: [gamma.cos(), beta.cos(), alpha.cos()], // cosAB, cosAC, cosBC
            atomic_species,
            lattice,
            atoms,
            kpoints: [nx, ny, nz],
        }
    }

    pub fn write_to<W: Write>(&self, writer: &mut W) -> io::Result<()> {
        writeln!(writer, "{}\n", self.header)?;

        writeln!(writer, "&CONTROL")?;
        writeln!(writer, "  title = '{}',", self.title)?;
        writeln!(
            writer,
            "  calculation = 'scf', prefix = '{}', outdir = './tmp', verbosity = 'high',",
            self.prefix
        )?;
        writeln!(
            writer,
            "  tprnfor = .true., tstress = .true., forc_conv_thr = 1.0d-7, etot_conv_thr = 1.0d-9, nstep = 100,"
        )?;
        writeln!(writer, "/\n")?;

        writeln!(writer, "&SYSTEM")?;
        writeln!(
            writer,
            "  ibrav = {}, nat = {}, ntyp = {},",
            self.ibrav, self.num_atoms, self.num_types
        )?;
        writeln!(
            writer,
            "  A = {:.10}, B = {:.10}, C = {:.10},",
            self.cell_abc[0], self.cell_abc[1], self.cell_abc[2]
        )?;
        writeln!(
            writer,
            "  cosAB = {:.10}, cosAC = {:.10}, cosBC = {:.10},",
            self.cell_cos_abc[0], self.cell_cos_abc[1], self.cell_cos_abc[2]
        )?;
        writeln!(
            writer,
            "  ecutwfc = 60, occupations = 'smearing', smearing = 'gauss', degauss = 1.0d-2,"
        )?;
        writeln!(writer, "/\n")?;

        writeln!(
            writer,
            "&ELECTRONS\n  conv_thr = 1.0d-12,\n  mixing_beta = 0.3d0,\n/\n"
        )?;
        writeln!(writer, "&IONS\n/\n")?;
        writeln!(writer, "&CELL\n  press_conv_thr = 0.02,\n/\n")?;

        writeln!(writer, "ATOMIC_SPECIES")?;
        for s in &self.atomic_species {
            writeln!(writer, "  {} {:.5} {}.upf", s.0, s.1, s.0)?;
        }
        writeln!(writer)?;

        writeln!(writer, "CELL_PARAMETERS (angstrom)")?;
        for row in &self.lattice {
            writeln!(writer, "  {:.10} {:.10} {:.10}", row[0], row[1], row[2])?;
        }
        writeln!(writer)?;

        writeln!(writer, "ATOMIC_POSITIONS (crystal)")?;
        for a in &self.atoms {
            writeln!(
                writer,
                "  {:2} {:.10} {:.10} {:.10}",
                a.0, a.1[0], a.1[1], a.1[2]
            )?;
        }
        writeln!(writer)?;

        writeln!(writer, "K_POINTS {{automatic}}")?;
        writeln!(
            writer,
            "  {} {} {} 0 0 0",
            self.kpoints[0], self.kpoints[1], self.kpoints[2]
        )?;

        Ok(())
    }
}

pub fn export_qe_input(state: &CrystalState, path: &str) -> io::Result<()> {
    let mut file = File::create(path)?;
    let qe = QeInputFile::from_state(state);
    qe.write_to(&mut file)
}
