//! Integration tests for format exporters (POSCAR, LAMMPS, QE)
use crystal_canvas::crystal_state::CrystalState;
use crystal_canvas::io::export::{export_lammps_data, export_poscar, export_qe_input};
use std::fs;

fn get_dummy_state() -> CrystalState {
    let mut state = CrystalState {
        name: "TestCrystal".to_string(),
        cell_a: 5.0, cell_b: 5.0, cell_c: 5.0,
        cell_alpha: 90.0, cell_beta: 90.0, cell_gamma: 90.0,
        spacegroup_hm: "P1".to_string(), spacegroup_number: 1,
        labels: vec![],
        elements: vec![],
        fract_x: vec![],
        fract_y: vec![],
        fract_z: vec![],
        occupancies: vec![],
        atomic_numbers: vec![],
        cart_positions: vec![],
        version: 1,
    };
    state.try_add_atom("Na", 11, [0.0, 0.0, 0.0]).unwrap();
    state.try_add_atom("Cl", 17, [0.5, 0.5, 0.5]).unwrap();
    state
}

#[test]
fn test_export_poscar() {
    let state = get_dummy_state();
    let path = "test_output.poscar";
    export_poscar(&state, path).unwrap();
    
    let content = fs::read_to_string(path).unwrap();
    fs::remove_file(path).unwrap();
    
    assert!(content.contains("TestCrystal generated by CrystalCanvas"));
    assert!(content.contains("1.0"));
    assert!(content.contains("Na Cl"));
    assert!(content.contains("1 1"));
    assert!(content.contains("Direct"));
    assert!(content.contains("0.000000 0.000000 0.000000"));
    assert!(content.contains("0.500000 0.500000 0.500000"));
}

#[test]
fn test_export_lammps() {
    let state = get_dummy_state();
    let path = "test_output.lammps";
    export_lammps_data(&state, path).unwrap();
    
    let content = fs::read_to_string(path).unwrap();
    fs::remove_file(path).unwrap();
    
    assert!(content.contains("# LAMMPS data file generated by CrystalCanvas"));
    assert!(content.contains("2 atoms"));
    assert!(content.contains("2 atom types"));
    assert!(content.contains("0.0 5.000000 xlo xhi"));
    assert!(content.contains("22.99000 # Na")); // Check mass lookup
    assert!(content.contains("35.45000 # Cl")); // Check mass lookup
    assert!(content.contains("Atoms # atomic"));
    assert!(content.contains("1 1 0.000000 0.000000 0.000000"));
}

#[test]
fn test_export_qe() {
    let state = get_dummy_state();
    let path = "test_output.in";
    export_qe_input(&state, path).unwrap();
    
    let content = fs::read_to_string(path).unwrap();
    fs::remove_file(path).unwrap();
    
    assert!(content.contains("! Quantum ESPRESSO input generated by CrystalCanvas"));
    assert!(content.contains("&CONTROL"));
    assert!(content.contains("calculation = 'scf', prefix = 'TestCrystal'"));
    assert!(content.contains("nat = 2, ntyp = 2"));
    assert!(content.contains("ATOMIC_SPECIES"));
    assert!(content.contains("Na 22.99000 Na.upf"));
    assert!(content.contains("ATOMIC_POSITIONS (crystal)"));
    assert!(content.contains("Na 0.0000000000 0.0000000000 0.0000000000"));
    assert!(content.contains("K_POINTS {automatic}"));
}
