//! [Overview: LLM Command enum definitions for serialization and deserialization]
// Copyright (c) 2026 Xiao Jiang and CrystalCanvas Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

use serde::{Deserialize, Serialize};

/// Supported export formats
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ExportFormat {
    Poscar,
    Lammps,
    Qe,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct DeleteAtomsParams {
    pub indices: Vec<u32>, // u32 enforces non-negative at type level
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct AddAtomParams {
    pub element: String,
    pub frac_pos: [f64; 3],
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SubstituteParams {
    pub indices: Vec<u32>,
    pub new_element: String,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct CleavSlabParams {
    pub miller: [i32; 3],
    pub layers: u32,
    pub vacuum_a: f64,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct MakeSupercellParams {
    pub matrix: [[i32; 3]; 3],
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ExportFileParams {
    pub format: ExportFormat,
    pub path: String,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct BatchParams {
    pub commands: Vec<CrystalCommand>,
}

/// The top-level command envelope generated by the LLM
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
#[serde(tag = "action", content = "params", deny_unknown_fields)]
#[serde(rename_all = "snake_case")]
pub enum CrystalCommand {
    DeleteAtoms(DeleteAtomsParams),
    AddAtom(AddAtomParams),
    Substitute(SubstituteParams),
    CleaveSlab(CleavSlabParams),
    MakeSupercell(MakeSupercellParams),
    ExportFile(ExportFileParams),
    Batch(BatchParams),
}
